// 孵蛋查询数据集（来源：roco-eggs.tsuki017.com 公开 species.json，宠物图已本地化）
// n 名称 | a 属性 | s 蛋尺寸区间[m] | w 蛋重量区间[kg] | e 蛋类型(normal/rideable/none) | evo 进化链 | al 别名 | img 本地图
const EGG_SPIRITS = [
  {"n": "喵喵", "a": ["草"], "s": [0.25, 0.3], "w": [1.494, 1.776], "e": ["normal", "rideable"], "evo": ["喵喵", "喵呜", "魔力猫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/喵喵.png"},
  {"n": "火花", "a": ["火"], "s": [0.25, 0.29], "w": [2.873, 3.4], "e": ["normal", "rideable"], "evo": ["火花", "焰火", "火神"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/火花.png"},
  {"n": "水蓝蓝", "a": ["水"], "s": [0.22, 0.24], "w": [1.161, 1.223], "e": ["normal", "rideable"], "evo": ["水蓝蓝", "波波拉", "水灵"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/水蓝蓝.png"},
  {"n": "鸭吉吉", "a": ["普通"], "s": [0.65, 0.94], "w": [14.6, 17.6], "e": ["normal"], "evo": ["鸭吉吉"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/鸭吉吉.png"},
  {"n": "板板壳", "a": ["水"], "s": [0.53, 0.76], "w": [7.5, 10.5], "e": ["normal", "rideable"], "evo": ["板板壳", "咔咔壳", "水泡壳"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/板板壳.png"},
  {"n": "锥尾羊", "a": ["幽"], "s": [0.57, 0.81], "w": [13.3, 16.5], "e": ["normal", "rideable"], "evo": ["锥尾羊", "铃兰羊", "花影羚羊"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/锥尾羊.png"},
  {"n": "雪绒鸟", "a": ["翼"], "s": [0.38, 0.51], "w": [2.77, 4.5], "e": ["normal", "rideable"], "evo": ["雪绒鸟", "冬羽雀", "岚鸟"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/雪绒鸟.png"},
  {"n": "小灵菇", "a": ["幽"], "s": [0.43, 0.61], "w": [5.4, 7.1], "e": ["normal"], "evo": ["小灵菇", "幻灵菇", "幻影灵菇"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小灵菇.png"},
  {"n": "石肤蜥", "a": ["地"], "s": [0.49, 0.7], "w": [21.0, 34.0], "e": ["normal", "rideable"], "evo": ["石肤蜥", "石刺蜥", "石冠王蜥"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/石肤蜥.png"},
  {"n": "布是石", "a": ["地"], "s": [0.42, 0.6], "w": [18.5, 32.5], "e": ["normal", "rideable"], "evo": ["布是石", "布是岩", "布克棱岩"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/布是石.png"},
  {"n": "恶魔叮", "a": ["恶", "翼"], "s": [0.39, 0.56], "w": [3.6, 5.2], "e": ["normal"], "evo": ["恶魔叮", "叮叮恶魔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/恶魔叮.png"},
  {"n": "毛毛", "a": ["虫", "萌"], "s": [0.31, 0.45], "w": [3.0, 4.5], "e": ["normal", "rideable"], "evo": ["毛毛", "爬爬", "化蝶"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/毛毛.png"},
  {"n": "幽影树", "a": ["幽", "草"], "s": [0.64, 0.92], "w": [29.5, 37.5], "e": ["normal"], "evo": ["幽影树"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/幽影树.png"},
  {"n": "小鼠獭", "a": ["普通", "水"], "s": [0.37, 0.53], "w": [6.7, 7.5], "e": ["normal", "rideable"], "evo": ["小鼠獭", "燕尾獭", "卷胡巨獭"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小鼠獭.png"},
  {"n": "矿晶虫", "a": ["光", "地"], "s": [0.54, 0.77], "w": [5.8, 10.53], "e": ["normal"], "evo": ["矿晶虫", "晶石蜗"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/矿晶虫.png"},
  {"n": "奇丽草", "a": ["草"], "s": [0.38, 0.55], "w": [4.09, 5.7], "e": ["normal", "rideable"], "evo": ["奇丽草", "奇丽叶", "奇丽花"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/奇丽草.png"},
  {"n": "丢丢", "a": ["草"], "s": [0.35, 0.51], "w": [4.3, 6.1], "e": ["normal", "rideable"], "evo": ["丢丢", "卡卡虫", "卡瓦重"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/丢丢.png"},
  {"n": "护主犬", "a": ["火"], "s": [0.64, 0.92], "w": [13.6, 17.5], "e": ["normal", "rideable"], "evo": ["护主犬", "音速犬"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/护主犬.png"},
  {"n": "绿耳松鼠", "a": ["普通"], "s": [0.47, 0.68], "w": [3.5, 6.0], "e": ["normal"], "evo": ["绿耳松鼠", "抱枕松鼠", "蹦床松鼠"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/绿耳松鼠.png"},
  {"n": "嘟嘟煲", "a": ["毒"], "s": [0.65, 0.8], "w": [48.5, 56.0], "e": ["normal"], "evo": ["嘟嘟煲", "嘟嘟锅"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/嘟嘟煲.png"},
  {"n": "小灵面", "a": ["幽"], "s": [0.38, 0.55], "w": [0.1, 0.55], "e": ["normal"], "evo": ["小灵面", "暗影灵面", "幽冥眼"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小灵面.png"},
  {"n": "梦游", "a": ["幽"], "s": [0.5, 0.6], "w": [0.6, 1.87], "e": ["normal", "rideable"], "evo": ["梦游", "梦悠悠"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/梦游.png"},
  {"n": "兽花蕾", "a": ["光", "草"], "s": [0.38, 0.45], "w": [4.25, 6.5], "e": ["normal"], "evo": ["兽花蕾"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/兽花蕾.png"},
  {"n": "伏地兽", "a": ["普通"], "s": [0.84, 1.21], "w": [21.6, 35.84], "e": ["normal", "rideable"], "evo": ["伏地兽", "贪食鼹", "巨噬针鼹"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/伏地兽.png"},
  {"n": "蹦蹦种子", "a": ["草", "毒"], "s": [0.46, 0.67], "w": [4.3, 5.6], "e": ["normal", "rideable"], "evo": ["蹦蹦种子", "蹦蹦草", "蹦蹦花"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/蹦蹦种子.png"},
  {"n": "电咩咩", "a": ["电"], "s": [0.58, 0.83], "w": [7.17, 9.1], "e": ["normal", "rideable"], "evo": ["电咩咩", "粉咩咩", "电球咩咩"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/电咩咩.png"},
  {"n": "蒲公英", "a": ["草", "萌"], "s": [0.3, 0.5], "w": [0.1, 0.6], "e": ["normal", "rideable"], "evo": ["蒲公英", "蒲公英娃娃"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/蒲公英.png"},
  {"n": "伊贝儿", "a": ["草"], "s": [0.44, 0.62], "w": [3.3, 4.2], "e": ["normal"], "evo": ["伊贝儿", "伊贝粉粉"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/伊贝儿.png"},
  {"n": "白发懒人", "a": ["普通"], "s": [0.72, 1.03], "w": [19.5, 23.5], "e": ["normal", "rideable"], "evo": ["白发懒人", "动力猿", "瞌睡王"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/白发懒人.png"},
  {"n": "海盔虫", "a": ["水", "毒"], "s": [0.55, 0.7], "w": [7.4, 8.6], "e": ["normal"], "evo": ["海盔虫", "刺盔虫", "千棘盔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/海盔虫.png"},
  {"n": "菊花梨", "a": ["萌"], "s": [0.63, 0.9], "w": [4.2, 5.8], "e": ["normal"], "evo": ["菊花梨"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/菊花梨.png"},
  {"n": "小星光", "a": ["电"], "s": [0.78, 1.12], "w": [27.5, 36.2], "e": ["normal"], "evo": ["小星光", "星光狮"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小星光.png"},
  {"n": "一窝蜂", "a": ["虫", "翼"], "s": [0.37, 0.52], "w": [4.0, 5.5], "e": ["normal", "rideable"], "evo": ["一窝蜂", "黄蜂后", "花魁蜂后"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/一窝蜂.png"},
  {"n": "小夜", "a": ["恶"], "s": [0.51, 0.73], "w": [4.5, 7.6], "e": ["normal"], "evo": ["小夜", "紫夜", "朔夜伊芙"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小夜.png"},
  {"n": "乖乖鹄", "a": ["翼", "水"], "s": [0.46, 0.67], "w": [4.2, 5.5], "e": ["normal"], "evo": ["乖乖鹄", "蓝珠天鹅", "翠顶夫人", "黑羽夫人"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/乖乖鹄.png"},
  {"n": "锤头鹳", "a": ["翼", "水"], "s": [1.09, 1.56], "w": [51.3, 65.8], "e": ["normal"], "evo": ["锤头鹳"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/锤头鹳.png"},
  {"n": "绿草精灵", "a": ["草", "幻"], "s": [0.71, 1.01], "w": [9.3, 10.3], "e": ["normal"], "evo": ["绿草精灵", "魔草巫灵"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/绿草精灵.png"},
  {"n": "记忆石", "a": ["地"], "s": [0.97, 1.39], "w": [90.2, 112.0], "e": ["normal", "rideable"], "evo": ["记忆石", "咔咔羽毛", "咔咔雀", "咔咔鸟"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/记忆石.png"},
  {"n": "小草虫", "a": ["虫", "草"], "s": [0.47, 0.67], "w": [2.1, 3.4], "e": ["normal"], "evo": ["小草虫", "草衣虫", "花衣蝶"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小草虫.png"},
  {"n": "绿翼鸟", "a": ["萌", "翼"], "s": [0.49, 0.61], "w": [3.6, 4.8], "e": ["normal"], "evo": ["绿翼鸟", "魔翼鸟", "魔眷鸟"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/绿翼鸟.png"},
  {"n": "阿米亚特", "a": ["地"], "s": [0.57, 0.79], "w": [38.5, 49.2], "e": ["normal", "rideable"], "evo": ["阿米亚特", "阿米樱", "罗隐"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/阿米亚特.png"},
  {"n": "风铃鲨", "a": ["水", "翼"], "s": [0.41, 0.59], "w": [13.07, 16.8], "e": ["normal", "rideable"], "evo": ["风铃鲨", "蓝蝶鲨", "彩蝶鲨"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/风铃鲨.png"},
  {"n": "石石", "a": ["地"], "s": [0.35, 0.5], "w": [61.0, 75.0], "e": ["normal", "rideable"], "evo": ["石石", "巨灵石"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/石石.png"},
  {"n": "仪使者", "a": ["地", "幻"], "s": [0.45, 0.58], "w": [19.05, 35.05], "e": ["normal", "rideable"], "evo": ["仪使者", "仪式之星", "仪式巨像"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/仪使者.png"},
  {"n": "小独角兽", "a": ["光"], "s": [0.98, 1.41], "w": [41.5, 55.6], "e": ["normal", "rideable"], "evo": ["小独角兽", "白金独角兽"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小独角兽.png"},
  {"n": "旋叶虫", "a": ["普通", "虫"], "s": [0.1, 0.15], "w": [0.1, 0.85], "e": ["normal"], "evo": ["旋叶虫", "蓬叶虫", "风滚暮虫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/旋叶虫.png"},
  {"n": "小黑猫", "a": ["普通"], "s": [0.55, 0.65], "w": [3.1, 4.5], "e": ["normal"], "evo": ["小黑猫", "黑猫巫师"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小黑猫.png"},
  {"n": "忽幽狸", "a": ["幽", "毒"], "s": [0.76, 1.09], "w": [8.3, 9.8], "e": ["normal"], "evo": ["忽幽狸", "影狸"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/忽幽狸.png"},
  {"n": "多多", "a": ["毒", "地"], "s": [0.45, 0.65], "w": [14.6, 18.6], "e": ["normal"], "evo": ["多多", "多啦多", "古啦多"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/多多.png"},
  {"n": "哭哭菇", "a": ["幻"], "s": [0.33, 0.47], "w": [1.8, 3.2], "e": ["normal", "rideable"], "evo": ["哭哭菇", "怖须菇", "怖哭菇"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/哭哭菇.png"},
  {"n": "恶魔狼", "a": ["恶"], "s": [1.23, 1.76], "w": [74.0, 92.0], "e": ["normal", "rideable"], "evo": ["恶魔狼"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/恶魔狼.png"},
  {"n": "小电企鹅", "a": ["冰", "电"], "s": [0.44, 0.56], "w": [3.82, 5.39], "e": ["normal"], "evo": ["小电企鹅", "电企鹅"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小电企鹅.png"},
  {"n": "雪豆丁", "a": ["冰"], "s": [0.86, 1.23], "w": [9.5, 12.5], "e": ["normal", "rideable"], "evo": ["雪豆丁", "雪蛮人", "雪巨人"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/雪豆丁.png"},
  {"n": "呼呼猪", "a": ["冰", "地"], "s": [0.52, 0.75], "w": [6.8, 8.9], "e": ["normal", "rideable"], "evo": ["呼呼猪", "獠牙猪"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/呼呼猪.png"},
  {"n": "雪娃娃", "a": ["冰"], "s": [0.29, 0.42], "w": [6.8, 8.16], "e": ["normal"], "evo": ["雪娃娃", "冰封怨灵", "雪灵"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/雪娃娃.png"},
  {"n": "大耳帽兜", "a": ["冰", "萌"], "s": [0.39, 0.42], "w": [8.39, 10.7], "e": ["normal"], "evo": ["大耳帽兜", "帽兜娃娃", "雪影娃娃"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/大耳帽兜.png"},
  {"n": "权杖-Ⅱ", "a": ["机械"], "s": [0.45, 0.55], "w": [28.5, 35.7], "e": ["normal"], "evo": ["权杖-Ⅱ", "权杖-Ⅴ"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/权杖-Ⅱ.png"},
  {"n": "灵狐", "a": ["火", "冰"], "s": [0.56, 0.8], "w": [7.4, 8.9], "e": ["normal"], "evo": ["灵狐", "九尾狐", "尖嘴狐仙"], "al": ["圣羽翼王", "灵羽勇士", "里奥"], "img": "https://roco-eggs.tsuki017.com/pet-images/灵狐.png"},
  {"n": "里奥", "a": ["翼"], "s": [0.35, 0.45], "w": [4.8, 5.9], "e": ["rideable", "none"], "evo": ["里奥", "灵狐"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/里奥.png"},
  {"n": "松仔", "a": ["草", "武"], "s": [0.52, 0.68], "w": [6.25, 7.85], "e": ["normal", "rideable"], "evo": ["松仔", "松叶羊", "针叶巡林"], "al": ["小勇狮", "炽心勇狮", "炽焰狮"], "img": "https://roco-eggs.tsuki017.com/pet-images/松仔.png"},
  {"n": "小勇狮", "a": ["火", "武"], "s": [0.67, 0.81], "w": [8.5, 12.05], "e": ["normal", "rideable"], "evo": ["小勇狮", "松仔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小勇狮.png"},
  {"n": "水滴蛇", "a": ["水", "武"], "s": [0.53, 0.69], "w": [2.25, 4.1], "e": ["normal", "rideable"], "evo": ["水滴蛇", "水蛇锁", "游蛇魔使"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/水滴蛇.png"},
  {"n": "公平鸽", "a": ["普通"], "s": [0.45, 0.6], "w": [2.5, 3.94], "e": ["normal"], "evo": ["公平鸽"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/公平鸽.png"},
  {"n": "小怂猫", "a": ["武"], "s": [0.59, 0.84], "w": [19.6, 22.5], "e": ["normal", "rideable"], "evo": ["小怂猫", "怒目怂猫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小怂猫.png"},
  {"n": "小狮鹫", "a": ["翼"], "s": [0.71, 1.02], "w": [11.5, 17.5], "e": ["normal", "rideable"], "evo": ["小狮鹫", "神圣狮鹫", "皇家狮鹫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小狮鹫.png"},
  {"n": "圆眼蜘蛛", "a": ["虫"], "s": [0.48, 0.68], "w": [3.5, 5.0], "e": ["normal"], "evo": ["圆眼蜘蛛", "尖角蜘蛛", "芋香巨角蛛"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/圆眼蜘蛛.png"},
  {"n": "波波螺", "a": ["地", "水"], "s": [0.32, 0.42], "w": [4.85, 5.65], "e": ["normal", "rideable"], "evo": ["波波螺", "消波螺", "嗜波螺"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/波波螺.png"},
  {"n": "菇菇丁", "a": ["地", "草"], "s": [0.25, 0.35], "w": [1.1, 2.76], "e": ["normal", "rideable"], "evo": ["菇菇丁", "多菇丁", "九幽菇"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/菇菇丁.png"},
  {"n": "斑斑", "a": ["翼"], "s": [0.47, 0.6], "w": [4.79, 6.17], "e": ["normal"], "evo": ["斑斑", "斑枭"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/斑斑.png"},
  {"n": "草头鸭", "a": ["草"], "s": [0.5, 0.72], "w": [4.9, 6.57], "e": ["normal"], "evo": ["草头鸭", "卷毛鸭"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/草头鸭.png"},
  {"n": "海豹战士", "a": ["武", "水"], "s": [0.64, 0.92], "w": [69.5, 87.6], "e": ["normal"], "evo": ["海豹战士", "海豹船长"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/海豹战士.png"},
  {"n": "号儿鱼", "a": ["水"], "s": [0.31, 0.42], "w": [3.9, 5.52], "e": ["normal"], "evo": ["号儿鱼", "圆号鱼"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/号儿鱼.png"},
  {"n": "甜田螺", "a": ["水", "萌"], "s": [0.41, 0.58], "w": [7.5, 9.4], "e": ["normal"], "evo": ["甜田螺", "壳乙螺", "卡洛儿"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/甜田螺.png"},
  {"n": "棋棋", "a": ["武", "地"], "s": [0.35, 0.47], "w": [10.7, 14.5], "e": ["normal", "rideable"], "evo": ["棋棋", "棋骑士", "棋齐垒", "棋祈督", "棋绮后"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/棋棋.png"},
  {"n": "奔波鼠", "a": ["地"], "s": [0.46, 0.6], "w": [3.71, 6.4], "e": ["normal"], "evo": ["奔波鼠", "流浪鼠"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/奔波鼠.png"},
  {"n": "呆小路", "a": ["草", "萌"], "s": [0.58, 0.83], "w": [4.5, 5.8], "e": ["normal"], "evo": ["呆小路", "舞动路路", "白发路路"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/呆小路.png"},
  {"n": "逗逗", "a": ["萌"], "s": [0.3, 0.4], "w": [0.45, 1.53], "e": ["normal", "rideable"], "evo": ["逗逗", "气球猫", "梦想三三"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/逗逗.png"},
  {"n": "花怨鳗", "a": ["地", "草"], "s": [0.58, 0.68], "w": [2.9, 4.0], "e": ["normal", "rideable"], "evo": ["花怨鳗", "鳗尾兽"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/花怨鳗.png"},
  {"n": "伊雷龙", "a": ["龙"], "s": [0.72, 0.94], "w": [27.2, 34.0], "e": ["normal"], "evo": ["伊雷龙", "伊兰亚龙"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/伊雷龙.png"},
  {"n": "拉特", "a": ["电"], "s": [0.49, 0.61], "w": [7.7, 8.6], "e": ["normal"], "evo": ["拉特", "酷拉"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/拉特.png"},
  {"n": "闪电环", "a": ["电"], "s": [0.37, 0.46], "w": [2.4, 3.1], "e": ["normal"], "evo": ["闪电环", "刺电环", "荆棘电环"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/闪电环.png"},
  {"n": "小箱怪", "a": ["机械", "幻"], "s": [0.34, 0.46], "w": [4.45, 6.81], "e": ["normal", "rideable"], "evo": ["小箱怪", "迷迷箱怪"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小箱怪.png"},
  {"n": "古钟蛇", "a": ["萌", "毒"], "s": [0.95, 1.1], "w": [6.9, 7.8], "e": ["normal", "rideable"], "evo": ["古钟蛇", "寒音蛇"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/古钟蛇.png"},
  {"n": "矮脚爬爬", "a": ["虫"], "s": [0.28, 0.44], "w": [3.3, 4.2], "e": ["normal", "rideable"], "evo": ["矮脚爬爬", "恶魔红钻"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/矮脚爬爬.png"},
  {"n": "火尾瓦特", "a": ["火"], "s": [0.64, 0.92], "w": [18.5, 21.2], "e": ["normal"], "evo": ["火尾瓦特", "火尾战士", "烈火守护"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/火尾瓦特.png"},
  {"n": "里拉鳐", "a": ["水"], "s": [0.94, 1.1], "w": [38.6, 49.5], "e": ["normal"], "evo": ["里拉鳐"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/里拉鳐.png"},
  {"n": "海枝枝", "a": ["水", "幽"], "s": [0.75, 0.85], "w": [3.51, 6.82], "e": ["normal"], "evo": ["海枝枝"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/海枝枝.png"},
  {"n": "多西", "a": ["机械", "地"], "s": [0.65, 0.94], "w": [5.7, 7.1], "e": ["normal", "rideable"], "evo": ["多西", "库多西", "波多西"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/多西.png"},
  {"n": "小翼龙", "a": ["龙", "翼"], "s": [0.61, 0.87], "w": [25.1, 36.5], "e": ["normal", "rideable"], "evo": ["小翼龙", "翼龙"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小翼龙.png"},
  {"n": "电动长颈鹿", "a": ["电"], "s": [0.7, 1.0], "w": [29.8, 36.8], "e": ["normal", "rideable"], "evo": ["电动长颈鹿", "奔乐鹿", "爵士鹿"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/电动长颈鹿.png"},
  {"n": "缇塔", "a": ["机械"], "s": [0.65, 0.75], "w": [38.2, 45.2], "e": ["normal"], "evo": ["缇塔", "声波缇塔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/缇塔.png"},
  {"n": "小鹬", "a": ["翼"], "s": [0.25, 0.36], "w": [1.4, 2.2], "e": ["normal"], "evo": ["小鹬", "鄙目鹬", "高脚鹬"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小鹬.png"},
  {"n": "脆筒甜甜", "a": ["冰"], "s": [0.3, 0.4], "w": [1.8, 3.8], "e": ["normal"], "evo": ["脆筒甜甜", "香草甜甜", "圣代甜甜"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/脆筒甜甜.png"},
  {"n": "刺轮砣", "a": ["毒", "萌"], "s": [0.18, 0.31], "w": [2.7, 4.0], "e": ["normal", "rideable"], "evo": ["刺轮砣", "月亮砣"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/刺轮砣.png"},
  {"n": "豆丁鱼", "a": ["水", "龙"], "s": [0.31, 0.44], "w": [1.2, 3.4], "e": ["normal", "rideable"], "evo": ["豆丁鱼", "快鳍鱼", "龙鱼"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/豆丁鱼.png"},
  {"n": "胆小鳗鱼", "a": ["电", "水"], "s": [0.74, 1.07], "w": [17.5, 26.85], "e": ["normal"], "evo": ["胆小鳗鱼", "闪电鳗鱼"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/胆小鳗鱼.png"},
  {"n": "翡翠水母", "a": ["水", "毒"], "s": [0.49, 0.7], "w": [31.5, 36.8], "e": ["normal"], "evo": ["翡翠水母", "琉璃水母"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/翡翠水母.png"},
  {"n": "裘洛", "a": ["毒"], "s": [0.7, 1.0], "w": [7.5, 12.5], "e": ["normal", "rideable"], "evo": ["裘洛", "裘力", "裘卡"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/裘洛.png"},
  {"n": "可爱猿", "a": ["火"], "s": [0.69, 0.98], "w": [21.0, 31.5], "e": ["normal", "rideable"], "evo": ["可爱猿", "炽热猿", "火焰猿"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/可爱猿.png"},
  {"n": "布鲁斯", "a": ["冰"], "s": [0.53, 0.76], "w": [2.4, 4.6], "e": ["normal", "rideable"], "evo": ["布鲁斯", "雪顶布鲁斯", "冰钻布鲁斯"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/布鲁斯.png"},
  {"n": "治愈兔", "a": ["火", "萌"], "s": [0.57, 0.82], "w": [12.03, 14.42], "e": ["normal"], "evo": ["治愈兔", "红丝绒", "红绒十字"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/治愈兔.png"},
  {"n": "乌达", "a": ["恶", "火"], "s": [0.44, 0.58], "w": [4.6, 6.1], "e": ["normal", "rideable"], "evo": ["乌达", "迷你乌", "乌拉塔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/乌达.png"},
  {"n": "螺旋帕帕", "a": ["机械", "翼"], "s": [0.35, 0.45], "w": [2.08, 4.35], "e": ["normal", "rideable"], "evo": ["螺旋帕帕", "帕帕斯卡"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/螺旋帕帕.png"},
  {"n": "机械方方", "a": ["机械"], "s": [0.42, 0.6], "w": [8.0, 11.0], "e": ["normal", "rideable"], "evo": ["机械方方", "多彩方方", "立方人"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/机械方方.png"},
  {"n": "可立鸡", "a": ["火"], "s": [0.39, 0.56], "w": [4.6, 7.4], "e": ["normal", "rideable"], "evo": ["可立鸡", "晕晕鸡", "绅士鸡", "武者鸡"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/可立鸡.png"},
  {"n": "优优", "a": ["地", "光"], "s": [0.38, 0.56], "w": [3.03, 4.09], "e": ["normal"], "evo": ["优优", "绒光优优"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/优优.png"},
  {"n": "噼啪鸟", "a": ["电", "翼"], "s": [2.0, 2.15], "w": [89.5, 127.5], "e": ["normal", "rideable"], "evo": ["噼啪鸟"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/噼啪鸟.png"},
  {"n": "深蓝鲸", "a": ["水"], "s": [2.0, 2.65], "w": [645.0, 700.0], "e": ["normal", "rideable"], "evo": ["深蓝鲸"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/深蓝鲸.png"},
  {"n": "格兰种子", "a": ["草"], "s": [0.4, 0.57], "w": [3.5, 5.4], "e": ["normal"], "evo": ["格兰种子", "格兰花", "格兰球"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/格兰种子.png"},
  {"n": "地鼠", "a": ["地"], "s": [0.46, 0.66], "w": [3.8, 5.13], "e": ["normal"], "evo": ["地鼠", "遁鼠", "遁地鼠"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/地鼠.png"},
  {"n": "墨鱿士", "a": ["幽"], "s": [0.35, 0.46], "w": [3.25, 5.02], "e": ["normal", "rideable"], "evo": ["墨鱿士", "混乱鱿彩", "秩序鱿墨"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/墨鱿士.png"},
  {"n": "小甲虫", "a": ["虫"], "s": [0.48, 0.68], "w": [6.5, 8.4], "e": ["normal", "rideable"], "evo": ["小甲虫", "铠甲虫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小甲虫.png"},
  {"n": "圣剑侍从", "a": ["机械"], "s": [0.94, 1.18], "w": [115.7, 173.6], "e": ["normal", "rideable"], "evo": ["圣剑侍从", "圣剑-X"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/圣剑侍从.png"},
  {"n": "吸泥鸥", "a": ["地", "翼"], "s": [0.55, 0.71], "w": [9.5, 12.5], "e": ["normal"], "evo": ["吸泥鸥", "泥吼牙"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/吸泥鸥.png"},
  {"n": "大头骨龙", "a": ["龙", "幽"], "s": [0.85, 1.0], "w": [18.6, 33.5], "e": ["normal", "rideable"], "evo": ["大头骨龙", "寂灭骨龙"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/大头骨龙.png"},
  {"n": "厉毒小萝", "a": ["毒", "恶"], "s": [0.55, 0.65], "w": [8.73, 14.92], "e": ["normal"], "evo": ["厉毒小萝", "厉毒修萝"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/厉毒小萝.png"},
  {"n": "小帕尔", "a": ["恶"], "s": [0.64, 0.92], "w": [9.4, 13.6], "e": ["rideable", "none"], "evo": ["小帕尔", "帕尔萨斯", "龙息帕尔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/小帕尔.png"},
  {"n": "毛头小蛛", "a": ["虫", "地"], "s": [0.3, 0.45], "w": [0.95, 2.0], "e": ["normal"], "evo": ["毛头小蛛", "捕尘长绒", "食尘短绒"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/毛头小蛛.png"},
  {"n": "画精灵", "a": ["普通"], "s": [0.28, 0.38], "w": [0.99, 2.21], "e": ["normal", "rideable"], "evo": ["画精灵", "画像守护", "画间法师手", "画间沉铁兽"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/画精灵.png"},
  {"n": "书魔虫", "a": ["普通"], "s": [0.3, 0.41], "w": [2.28, 3.86], "e": ["normal", "rideable"], "evo": ["书魔虫", "书卷守护", "古卷执政官", "古卷匣魔像"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/书魔虫.png"},
  {"n": "绒绒", "a": ["光", "虫"], "s": null, "w": null, "e": ["rideable", "none"], "evo": ["绒绒", "小绒茧", "绒仙子"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/绒绒.png"},
  {"n": "犀角鸟", "a": ["光"], "s": [0.32, 0.4], "w": [9.6, 11.5], "e": ["rideable", "none"], "evo": ["犀角鸟", "光纤兽", "疾光千兽"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/犀角鸟.png"},
  {"n": "果冻", "a": ["水"], "s": [0.3, 0.36], "w": [4.35, 5.6], "e": ["normal"], "evo": ["果冻", "抹茶布丁", "椰浆布丁", "熔岩布丁"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/果冻.png"},
  {"n": "星尘虫", "a": ["虫"], "s": [0.15, 0.2], "w": [0.45, 1.4], "e": ["normal", "rideable"], "evo": ["星尘虫", "落星虫", "陨星虫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/星尘虫.png"},
  {"n": "双灯鱼", "a": ["水", "电"], "s": [0.5, 0.72], "w": [14.9, 17.8], "e": ["normal"], "evo": ["双灯鱼", "利灯鱼"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/双灯鱼.png"},
  {"n": "月牙雪熊", "a": ["冰", "幻"], "s": [1.25, 1.45], "w": [76.5, 92.5], "e": ["normal", "rideable"], "evo": ["月牙雪熊"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/月牙雪熊.png"},
  {"n": "嗜光嗡嗡", "a": ["恶", "光"], "s": [0.24, 0.32], "w": [1.46, 3.05], "e": ["normal"], "evo": ["嗜光嗡嗡", "窃光蚊"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/嗜光嗡嗡.png"},
  {"n": "柴渣虫", "a": ["火", "草"], "s": [0.45, 0.55], "w": [14.5, 18.6], "e": ["normal"], "evo": ["柴渣虫", "燃薪虫"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/柴渣虫.png"},
  {"n": "空空颅", "a": ["幽"], "s": [0.42, 0.61], "w": [5.6, 8.7], "e": ["normal", "rideable"], "evo": ["空空颅", "夜宿颅", "夜枭"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/空空颅.png"},
  {"n": "粉粉星", "a": ["电", "幻"], "s": [0.53, 0.76], "w": [2.1, 3.0], "e": ["normal"], "evo": ["粉粉星", "小皮球"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/粉粉星.png"},
  {"n": "贝瑟", "a": ["机械", "火"], "s": [0.57, 0.82], "w": [24.5, 34.6], "e": ["normal", "rideable"], "evo": ["贝瑟", "贝加尔", "贝古斯"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/贝瑟.png"},
  {"n": "粉星仔", "a": ["幻"], "s": [0.39, 0.5], "w": [9.8, 12.8], "e": ["normal", "rideable"], "evo": ["粉星仔", "粉耳星兔", "落陨星兔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/粉星仔.png"},
  {"n": "火红尾", "a": ["火"], "s": [0.72, 0.98], "w": [17.5, 30.5], "e": ["normal"], "evo": ["火红尾", "雅丹鬃"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/火红尾.png"},
  {"n": "春团", "a": ["草"], "s": [0.35, 0.51], "w": [2.1, 3.6], "e": ["normal"], "evo": ["春团", "春兔", "春花兔"], "al": [], "img": "https://roco-eggs.tsuki017.com/pet-images/春团.png"},
];
